"""remoçao da coluna imagem da tabela receita

Revision ID: 0d60c821e166
Revises: fe879b97a7d1
Create Date: 2025-12-09 19:25:25.857605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d60c821e166'
down_revision: Union[str, Sequence[str], None] = 'fe879b97a7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receitas', 'imagem_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receitas', sa.Column('imagem_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
