"""imagem

Revision ID: fe879b97a7d1
Revises: 
Create Date: 2025-12-05 19:55:38.180309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe879b97a7d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.add_column('receitas', sa.Column('imagem_url', sa.String(), nullable=True))
    op.alter_column('receitas', 'nome_da_receita',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('receitas', 'ingredientes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('receitas', 'modo_de_preparo',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.create_index(op.f('ix_receitas_nome_da_receita'), 'receitas', ['nome_da_receita'], unique=False)
    op.alter_column('usuarios', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_receitas_nome_da_receita'), table_name='receitas')
    op.alter_column('receitas', 'modo_de_preparo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receitas', 'ingredientes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('receitas', 'nome_da_receita',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('receitas', 'imagem_url')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
